jobs:
  install:
    docker:
      - image: circleci/node:6.10.3
        user: root
    steps:
      - checkout
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Install build essential
          command: apt-get install -y build-essential
      - run:
          name: Use NPM Registry
          command: echo "registry=https://registry.npmjs.org/" > ~/.npmrc
      - run:
          name: Install dependencies
          command: yarn install --pure-lockfile
      - run:
          name: Install bcrypt
          command: npm install bcrypt
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - "~/.npm"
            - "node_modules"

  docs:
    docker:
      - image: circleci/node:6.10.3
        user: root
    steps:
      - checkout
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Generate documentation
          command: yarn doc
      - store_artifacts:
          path: docs
          destination: documentation
      - save_cache:
          key: docs-{{ .Branch }}-{{ .Revision }}
          paths:
            - docs

  lint:
    docker:
      - image: circleci/node:6.10.3
        user: root
    steps:
      - checkout
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Run Lint
          command: yarn lint

  test:
    docker:
      - image: circleci/node:6.10.3
        user: root
      - image: mongo:3.4.6
      - image: rabbitmq:3.6-management-alpine
    steps:
      - checkout
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Run tests
          command: yarn test
      - store_artifacts:
          path: coverage
          destination: coverage
      - save_cache:
          key: coverage-{{ checksum "coverage/lcov.info" }}
          paths: coverage

  coveralls:
    docker:
      - image: circleci/node:6.10.3
        user: root
    steps:
      - checkout
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}
      - restore_cache:
          key: coverage
      - run:
          name: Install coverage
          command: npm install -g coveralls
      - run:
          name: Update coverage
          command: cat ./coverage/lcov.info | coveralls

  codacy:
    docker:
      - image: circleci/node:6.10.3
        user: root
    steps:
      - checkout
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}
      - restore_cache:
          key: coverage
      - run:
          name: Install coverage
          command: npm install -g codacy-coverage
      - run:
          name: Update coverage
          command: cat ./coverage/lcov.info | codacy-coverage

  deploy_docs:
    docker:
      - image: circleci/python:2.7
        user: root
    steps:
      - checkout
      - restore_cache:
          key: docs-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Install AWS CLI
          command: apt-get update && apt-get install -y awscli
      - deploy:
          name: Sync documentation
          command: aws s3 sync docs s3://ogma-api/docs/ --region eu-west-1 --delete

workflows:
  version: 2
  full_workflow:
    jobs:
      - install
      - lint:
          requires:
            - install
      - docs:
          requires:
            - install
      - test:
          requires:
            - install
      - coveralls:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - codacy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - deploy_docs:
          requires:
            - docs
          filters:
            branches:
              only:
                - master
